<?xml version="1.0"?>
<package format="3">

  <name>robot1_nav</name>
  <version>0.0.1</version>

  <description>
    Nav2 package for Robot1 smart walker
  </description>

  <maintainer email="jet@ubuntu.local">jet</maintainer>

  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  
  
  <depend>rclcpp</depend>
  <depend>std_msgs</depend>
  <depend>geometry_msgs</depend>
  <depend>ament_index_cpp</depend>
  <depend>nlohmann-json-dev</depend>
  <depend>rclcpp_action</depend>
  <depend>nav2_msgs</depend>
  <depend>sensor_msgs</depend>
  <depend>nav_msgs</depend>
  <depend>tf2</depend>
  <depend>tf2_ros</depend>

  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>ament_index_python</exec_depend>
  <exec_depend>laser_filters</exec_depend>
  <exec_depend>robot1_core</exec_depend>
  <exec_depend>rplidar_ros</exec_depend>
  <exec_depend>stella_ahrs</exec_depend>
  <exec_depend>rviz2</exec_depend>
  <exec_depend>nav2_bringup</exec_depend>

  <exec_depend>nav2_map_server</exec_depend>
  <exec_depend>nav2_amcl</exec_depend>
  <exec_depend>nav2_controller</exec_depend>
  <exec_depend>nav2_smoother</exec_depend>
  <exec_depend>nav2_planner</exec_depend>
  <exec_depend>nav2_behaviors</exec_depend>
  <exec_depend>nav2_bt_navigator</exec_depend>
  <exec_depend>nav2_waypoint_follower</exec_depend>
  <exec_depend>nav2_velocity_smoother</exec_depend>
  <exec_depend>nav2_lifecycle_manager</exec_depend>
  <exec_depend>voice_nav_pkg</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>

</package>

