slam_toolbox:
  ros__parameters:

    # ==========================================================
    # Basic
    # ==========================================================

    use_sim_time: false

    mode: mapping

    odom_frame: robot1_odom
    map_frame: map
    base_frame: robot1_base

    scan_topic: /scan_filtered

    use_map_saver: true


    # ==========================================================
    # Ceres Solver
    # ==========================================================

    solver_plugin: solver_plugins::CeresSolver

    ceres_linear_solver: SPARSE_NORMAL_CHOLESKY
    ceres_preconditioner: SCHUR_JACOBI
    ceres_trust_strategy: LEVENBERG_MARQUARDT
    ceres_dogleg_type: TRADITIONAL_DOGLEG
    ceres_loss_function: None


    # ==========================================================
      # SLAM / TF
    # ==========================================================

    debug_logging: false

    #  실기에서는 TF/연산 지연을 받아줄 버퍼 확보
    scan_queue_size: 10

    # A2M12 약 10 Hz → SLAM에는 약 5 Hz 사용
    throttle_scans: 2

    transform_publish_period: 0.02

    map_update_interval: 1.0

    resolution: 0.05

    restamp_tf: false

    transform_timeout: 0.5

    tf_buffer_duration: 30.0

    stack_size_to_use: 40000000

    enable_interactive_mode: true


    # ==========================================================
    # LiDAR
    # ==========================================================

    min_laser_range: 0.20
    max_laser_range: 16.0


    # ==========================================================
    # Scan Matching
    #
    # Odom만 따라가지 않고
    # LaserScan으로 pose를 계속 보정
    # ==========================================================

    use_scan_matching: true

    use_scan_barycenter: true

    # 5 cm 이동마다 새로운 scan 처리 가능
    minimum_travel_distance: 0.05

    # 약 2.9도 회전마다 새로운 scan 처리 가능
    minimum_travel_heading: 0.05

    check_min_dist_and_heading_precisely: true


    # ==========================================================
    # Scan Buffer / Sequential Matching
    # ==========================================================

    scan_buffer_size: 20

    scan_buffer_maximum_scan_distance: 10.0

    link_match_minimum_response_fine: 0.10

    link_scan_maximum_distance: 1.5


    # ==========================================================
    # Loop Closure
    #
    # 한 바퀴 돌아 기존 구간으로 복귀하면
    # pose graph 전체 누적 오차 보정
    # ==========================================================

    do_loop_closing: true

    loop_search_maximum_distance: 4.0

    loop_match_minimum_chain_size: 10

    loop_match_maximum_variance_coarse: 3.0

    loop_match_minimum_response_coarse: 0.35

    loop_match_minimum_response_fine: 0.45


    # ==========================================================
    # Sequential Scan Correlation
    # ==========================================================

    correlation_search_space_dimension: 0.5

    correlation_search_space_resolution: 0.01

    correlation_search_space_smear_deviation: 0.1


    # ==========================================================
    # Loop Closure Search
    # ==========================================================

    loop_search_space_dimension: 8.0

    loop_search_space_resolution: 0.05

    loop_search_space_smear_deviation: 0.03


    # ==========================================================
    # Scan Matcher
    #
    # Odom과 scan matching 결과 차이에 대한 penalty
    # ==========================================================

    distance_variance_penalty: 0.5

    angle_variance_penalty: 1.0

    fine_search_angle_offset: 0.00349

    coarse_search_angle_offset: 0.349

    coarse_angle_resolution: 0.0349

    minimum_angle_penalty: 0.9

    minimum_distance_penalty: 0.5

    use_response_expansion: true


    # ==========================================================
    # Occupancy Grid
    # ==========================================================

    min_pass_through: 2

    occupancy_threshold: 0.1
